pipeline {
      agent{
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: maven
                image: maven:3.8.6-openjdk-11
                command:
                - sleep
                args:
                - infinity
                  '''
        }
      }
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
        stage('Build') { 
            steps {
            container(name: 'maven'){
                sh "mvn ${maven_goals}" 
            }
            }
        }
    }
/*
    post {
      // Email Ext plugin:
      success {  
        
        emailext (
            subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: "${emailRecipient}",
            from: "buildNotifications@emailaddress.com"
          )
      }

      failure {
        
        emailext (
            subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: "${emailRecipient}",
            from: "buildNotifications@emailaddress.com"
          )
      }
  } 
} */
