pipeline {
    agent{
      kubernetes{
      inheritFrom "${maven_template}"
      defaultContainer 'maven'
      }
    }
    stages {
        stage('Checkout') {
            steps {
              checkout scmGit(
                branches: [[name: ${github_branch}]],
                userRemoteConfigs: [[credentialsId:  ${github_creds},
                url: ${github_repo}]])
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
